!pip install sklearn

In [1]:
!pip install gensim

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621


# Part-of-speech tagging

### Import libraries

In [2]:
import os
import pandas as pd
import numpy as np
from scipy import spatial
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import pickle


### Download dataste

In [3]:
import urllib.request  #  download files
import zipfile  #  unzip files

dataset_folder = os.path.join(os.getcwd(), "OriginalDataset")

if not os.path.exists(dataset_folder):
    os.makedirs(dataset_folder)

url = 'https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/dependency_treebank.zip'

dataset_path = os.path.join(dataset_folder, "dependency_treebank.zip")

if not os.path.exists(dataset_path):
    urllib.request.urlretrieve(url, dataset_path)
    print("Successful download")

with zipfile.ZipFile(dataset_path,"r") as zip_ref:
    zip_ref.extractall(dataset_folder)
print("Successful extraction")

Successful extraction


### Split dataset

In [4]:
train_path = './Dataset/train/'# Should we use: os.path.join(os.getcwd(), "OriginalDataset")
val_path = './Dataset/val/'
test_path = './Dataset/test/'
original_path = dataset_folder +'/dependency_treebank/'

In [5]:
if not os.path.exists(train_path):
    print("making directory")
    os.makedirs(train_path)
if not os.path.exists(val_path):
    os.makedirs(val_path)
if not os.path.exists(test_path):
    os.makedirs(test_path)

In [6]:
original_dataset = os.listdir(original_path)

In [7]:
original_dataset.sort()
org_train = original_dataset[0:100]
org_val = original_dataset[100:150]
org_test = original_dataset[150:]

In [8]:
for f in org_train:
    os.rename(original_path+f, train_path+f)
for f in org_val:
    os.rename(original_path+f, val_path+f)
for f in org_test:
    os.rename(original_path+f, test_path+f)


### Preprocessing

In [9]:
def lower(lst): # DO WE NEED THIS?
    lowercase_list = [x.lower() for x in lst]
    return lowercase_list

### Create dataframe

In [10]:
def create_dataframe(dataset_path: str):
    dataframe_rows = []
    documents = os.listdir(dataset_path)
    for document in documents:
        path = os.path.join(dataset_path, document)
        with open(path, 'r') as f:
            a = [[x for x in ln.split()] for ln in f]
        a2 = [x for x in a if x != []] # OBS! Removing all empty lines in file so we can make an array
        arr = np.array(a2)
        text = arr[:, 0]
        tagg = arr[:, 1]
        #POStuple =  [tagg[x] for x in range(len(text))] #[(text[x], tagg[x]) for x in range(len(text))]
        document_id = int(document[4:8])
        dataframe_row = {
            "document_id": document_id,
            "text": text,
            "POS": tagg
        }
        dataframe_rows.append(dataframe_row)
    # transform the list of rows in a proper dataframe
    df = pd.DataFrame(dataframe_rows)
    df = df[["document_id", "text", "POS"]]

    return df

In [11]:
df_train = create_dataframe(train_path)
df_val = create_dataframe(val_path)
df_test = create_dataframe(test_path)

df_train

document_id                                               text  \
0            95  [In, reference, to, your, Oct., 9, page-one, a...   
1            37  [Judging, from, the, Americana, in, Haruki, Mu...   
2            66  [Sir, Peter, Walters, ,, 58-year-old, chairman...   
3            52  [PAPERS, :, Backe, Group, Inc., agreed, to, ac...   
4             3  [A, form, of, asbestos, once, used, to, make, ...   
..          ...                                                ...   
95           82  [Criticism, in, the, U.S., over, recent, Japan...   
96           71  [When, Warren, Winiarski, ,, proprietor, of, S...   
97           20  [The, U.S., ,, claiming, some, success, in, it...   
98           14  [Norman, Ricken, ,, 52, years, old, and, forme...   
99           45  [Since, chalk, first, touched, slate, ,, schoo...   

                                                  POS  
0   [IN, NN, TO, PRP$, NNP, CD, NN, NN, ``, NNP, N...  
1   [VBG, IN, DT, NNS, IN, NNP, NNP, POS, ``, DT, ...  
2   [NNP, NNP, NNP, ,, JJ, NN, IN, NNP, NNP, NNP, ...  
3   [NNS, :, NNP, NNP, NNP, VBD, TO, VB, NNP, NNP,...  
4   [DT, NN, IN, NN, RB, VBN, TO, VB, NNP, NN, NNS...  
..                                                ...  
95  [NNP, IN, DT, NNP, IN, JJ, JJ, NNS, VBZ, VBG, ...  
96  [WRB, NNP, NNP, ,, NN, IN, NNP, POS, NNP, NNP,...  
97  [DT, NNP, ,, VBG, DT, NN, IN, PRP$, NN, NN, ,,...  
98  [NNP, NNP, ,, CD, NNS, JJ, CC, JJ, NN, CC, NN,...  
99  [IN, NN, RB, VBD, NN, ,, NN, VBP, VBN, TO, VB,...  

[100 rows x 3 columns]

### Embed the words using GloVe embedding

embeddings_dict = {}

#### Load glove model

In [12]:
import gensim
import gensim.downloader as gloader

def load_embedding_model(embedding_dimension: int = 50) -> gensim.models.keyedvectors.KeyedVectors:
    download_path = "glove-wiki-gigaword-{}".format(embedding_dimension)
    # Check download
    try:
        emb_model = gloader.load(download_path)
    except ValueError as e:
        print("Invalid embedding model name! Check the embedding dimension:")
        print("Word2Vec: 300")
        print("Glove: 50, 100, 200, 300")
        raise e

    return emb_model

In [13]:
embedding_dimension = 50

embedding_model = load_embedding_model(embedding_dimension)

#### Get vocabulary

In [14]:
def get_word_list(data_frame, lable):
    big_list = []
    text = data_frame[lable]
    for row in data_frame[lable]:
        big_list += row.tolist()

    word_list = set(big_list)
    return word_list

In [15]:
word_list_train = get_word_list(df_train, "text")
word_list_val = get_word_list(df_val, "text")
word_list_test = get_word_list(df_test, "text")

In [16]:
"""---------------------OBS------------------------
Where shoukld we get tags? Is it ok to assume they are in df_train?
"""
tags_list = get_word_list(df_train, "POS")

#### Find OOV

In [17]:
# Function definition

def check_OOV_terms(embedding_model: gensim.models.keyedvectors.KeyedVectors,
                    word_list):
    """
    Checks differences between pre-trained embedding model vocabulary
    and dataset specific vocabulary in order to highlight out-of-vocabulary terms.

    :param embedding_model: pre-trained word embedding model (gensim wrapper)
    :param word_listing: dataset specific vocabulary (list)

    :return
        - list of OOV terms
    """
    embedding_vocabulary = set(embedding_model.index_to_key) # Was previously: set(embedding_model.vocab.keys())
    oov = set(word_list).difference(embedding_vocabulary)
    return list(oov)


In [18]:
oov1_terms = check_OOV_terms(embedding_model, word_list_train)
#--------------------------OBS--------------------------------------------#
# To make sure OOV2 does not contain words from OOV1 a check is 
# implemented during the embedding in the word to index function. 
# It might be an idea to include this check in the chekc_OOV_terms as well. 
# Question for the professor?
#--------------------------OBS--------------------------------------------#
oov2_terms = check_OOV_terms(embedding_model, word_list_val)
oov3_terms = check_OOV_terms(embedding_model, word_list_test)


print("Total OOV1 terms: {0} ({1:.2f}%)".format(len(oov1_terms), float(len(oov1_terms)) / len(word_list_train)))
print("Total OOV2 terms: {0} ({1:.2f}%)".format(len(oov2_terms), float(len(oov2_terms)) / len(word_list_train)))
print("Total OOV3 terms: {0} ({1:.2f}%)".format(len(oov3_terms), float(len(oov3_terms)) / len(word_list_train)))


Total OOV1 terms: 2346 (0.29%)
Total OOV2 terms: 1524 (0.19%)
Total OOV3 terms: 957 (0.12%)


### Create word_to_index (for one-hot encoding)

In [19]:
from collections import OrderedDict

def create_word_to_idx(vocabulary):
    word_to_idx = OrderedDict()
    idx_to_word = OrderedDict()
    word_to_idx["PADDING"] = 0
    idx_to_word[0] = "PADDING"
    # Start from one. Index 0 is reserved for padding
    current_idx = 1
    for word in vocabulary:
        if word not in word_to_idx:
            word_to_idx[word] = current_idx
            idx_to_word[current_idx] = word
            current_idx += 1
            
    return word_to_idx, idx_to_word

def update_word_to_idx(old_idx_to_word, old_word_to_idx, new_words):
    word_to_idx = old_word_to_idx.copy()
    idx_to_word = old_idx_to_word.copy()
    current_idx = len(word_to_idx)
    for word in new_words:
        if word not in word_to_idx:
            word_to_idx[word] = current_idx
            idx_to_word[current_idx] = word
            current_idx += 1
            
    return word_to_idx, idx_to_word
    

In [20]:
"""----------------------OBS------------------------------------
Should we also compute word to index for the test set and embed
these words, and then use all of them for training and validation
or should we keep the test set seperate and only compute this for
testing?
----------------------OBS------------------------------------"""
word_to_idx_v1, idx_to_word_v1 = create_word_to_idx(set(embedding_model.index_to_key))
word_to_idx_v2, idx_to_word_v2 = update_word_to_idx(idx_to_word_v1, word_to_idx_v1, oov1_terms)
word_to_idx_v3, idx_to_word_v3 = update_word_to_idx(idx_to_word_v2, word_to_idx_v2, oov2_terms)

tag_to_idx, idx_to_tag = create_word_to_idx(tags_list)

In [21]:
def save_idx_word_list(idx_to_word,word_to_idx, write_path):
    if not os.path.exists(os.path.dirname(write_path)):
        try:
            os.makedirs(os.path.dirname(write_path))
        except OSError as exc: # Guard against race condition
            if exc.errno != errno.EEXIST:
                raise
    with open(write_path, 'wb') as f:
        pickle.dump(obj={"word_to_idx": words_lexicon, "idx_to_word":idx_to_word} , file=f)

### Create embedding matrix

In [22]:
# OBS Computes the OOV with random embeddings
def create_embedding_matrix(embedding_model, embedding_dimension, word_to_idx):
    embedding_matrix = np.zeros((len(word_to_idx), embedding_dimension), dtype=np.float32)
    for word, idx in word_to_idx.items():
        try:
            embedding_vector = embedding_model[word]
        except (KeyError, TypeError):
            embedding_vector = np.random.uniform(low=-0.05, high=0.05, size=embedding_dimension)

        embedding_matrix[idx] = embedding_vector
                                
    return embedding_matrix

def expand_embedding_matrix(embedding_model, embedding_dimension, word_to_idx, old_embedding_matrix):
    embedding_matrix = np.zeros((len(word_to_idx), embedding_dimension), dtype=np.float32)
    embedding_matrix[0:len(old_embedding_matrix)] = old_embedding_matrix
    
    for word, idx in word_to_idx.items():
        if idx >= len(old_embedding_matrix):
            try:
                embedding_vector = embedding_model[word]
            except (KeyError, TypeError):
                embedding_vector = np.random.uniform(low=-0.05, high=0.05, size=embedding_dimension)
                
            embedding_matrix[idx] = embedding_vector
    
    return embedding_matrix                                

In [23]:
embedding_matrix_v1 = create_embedding_matrix(embedding_model, embedding_dimension, word_to_idx_v1)
embedding_matrix_v2 = expand_embedding_matrix(embedding_model, embedding_dimension, word_to_idx_v2, embedding_matrix_v1)
embedding_matrix_v3 = expand_embedding_matrix(embedding_model, embedding_dimension, word_to_idx_v3, embedding_matrix_v2)

print(embedding_matrix_v1.shape)
print(embedding_matrix_v2.shape)
print(embedding_matrix_v3.shape)


(400001, 50)
(402347, 50)
(403291, 50)


#### Test (Remove later)


In [24]:
vocab = ['Hello', 'Solveig', 'is', 'very', 'wierd', '.']

w_t_idx, idx_t_w = create_word_to_idx(vocab)
print(w_t_idx)

embed_matrix = create_embedding_matrix(None, 5, w_t_idx)
print(embed_matrix)

new_words = ['Andrea', 'is', 'super', 'cool', '.']
new_w_t_idx, new_idx_t_w = update_word_to_idx(idx_t_w, w_t_idx, new_words)
print(new_w_t_idx)

new_embed_matrix = expand_embedding_matrix(None, 5, new_w_t_idx, embed_matrix)
print(new_embed_matrix)

OrderedDict([('PADDING', 0), ('Hello', 1), ('Solveig', 2), ('is', 3), ('very', 4), ('wierd', 5), ('.', 6)])
[[ 0.01447313  0.01867697 -0.04413103  0.00786268 -0.01990556]
 [-0.01827857 -0.00304442  0.04012087 -0.01342806  0.00270245]
 [ 0.04026577  0.01137644 -0.03868113 -0.01408349 -0.02013893]
 [ 0.04675194  0.00669573  0.0399088  -0.04474164 -0.03553854]
 [-0.01097974 -0.04639542 -0.01038307 -0.01874456 -0.04105726]
 [-0.0180965   0.01993193 -0.04398752  0.03452281 -0.02659263]
 [-0.04814633  0.03362158 -0.01133895 -0.00290779  0.01320373]]
OrderedDict([('PADDING', 0), ('Hello', 1), ('Solveig', 2), ('is', 3), ('very', 4), ('wierd', 5), ('.', 6), ('Andrea', 7), ('super', 8), ('cool', 9)])
[[ 0.01447313  0.01867697 -0.04413103  0.00786268 -0.01990556]
 [-0.01827857 -0.00304442  0.04012087 -0.01342806  0.00270245]
 [ 0.04026577  0.01137644 -0.03868113 -0.01408349 -0.02013893]
 [ 0.04675194  0.00669573  0.0399088  -0.04474164 -0.03553854]
 [-0.01097974 -0.04639542 -0.01038307 -0.0187445

### Transform documents to sequences of integers

In [25]:
def sequence_to_integers(sequence, word_to_idx):
    integers = []
    for element in sequence:
        integers.append(word_to_idx[element])
    return np.array(integers)
"""OBS
Takes only one list of words to integer, not the list with lists.
"""

'OBS\nTakes only one list of words to integer, not the list with lists.\n'

In [26]:
# Make train text and tags into sequence of integers
train_text = df_train["text"]
train_tags = df_train["POS"]

#---------------OBS----------------------------------------------------------------
#  Should x_train be numpy array?
#  Should we use Word to index for V3 or V2???
#---------------OBS----------------------------------------------------------------
x_train = [sequence_to_integers(sequence, word_to_idx_v3) for sequence in train_text]
y_train = [sequence_to_integers(sequence, tag_to_idx) for sequence in train_tags]


val_text = df_val["text"]
val_tags = df_val["POS"]
x_val = [sequence_to_integers(sequence, word_to_idx_v3) for sequence in val_text]
y_val = [sequence_to_integers(sequence, tag_to_idx) for sequence in val_tags]

In [27]:
from keras.preprocessing.sequence import pad_sequences

def pad_idx_seqs(idx_seqs, max_seq_len):
    # Keras provides a convenient padding function; 
    padded_idxs = pad_sequences(sequences=idx_seqs, maxlen=max_seq_len)
    return padded_idxs

In [28]:
def find_max_length(seqs):
    max_len = 0
    for seq in seqs:
        if len(seq) > max_len:
            max_len = len(seq)
    return max_len

In [29]:
x_train = pad_idx_seqs(x_train, find_max_length(x_train))
y_train = pad_idx_seqs(y_train, find_max_length(y_train))

x_val = pad_idx_seqs(x_val, find_max_length(x_val))
y_val = pad_idx_seqs(y_val, find_max_length(y_val))




### Create baseline model

##### two layers architecture: a Bidirectional LSTM layer and a Dense/Fully-Connected layer on top

In [98]:
from tensorflow import keras
from tensorflow.keras import layers


def create_model(layers_info, compile_info) -> keras.Model:
    """
    Create a Keras model given a list of layer information

    :param layers_info: a list of dictionaries, one for each layer
    :param compile_info: dictionary containing compile information

    :return
        model: the built keras sequential model
    """

    print('Found {} total layers'.format(len(layers_info)))

    model = keras.Sequential()
    for info_idx, info in enumerate(layers_info):

        layer = info['layer'](**{key: value for key, value in info.items() if key != 'layer'})
        if info["name"] == "Bidirectional_LSTM_layer":
            model.add(layers.Bidirectional(layers.LSTM(64)))
        else:
            model.add(layer)

    # Debug
    model.summary()

    # Compile
    model.compile(**compile_info)

    return model

In [107]:
baseline_layers_info = [
    {
        "layer": layers.Embedding,
        "output_dim": embedding_dimension,
        "input_dim": len(word_to_idx_v3),
        "weights": [embedding_matrix_v3],
        "input_length": find_max_length(x_train),
        "mask_zero": True, # Because of padding
        "name": "embedding_layer"
    },
    {
        "layer": layers.LSTM,
        "units": 50,
        "name": "Bidirectional_LSTM_layer"
    },
    {
        "layer": layers.Dense,
        "units": len(tag_to_idx),
        "activation": "softmax",
        "name": "Dense_layer"
    }
]

compile_info = {
    'optimizer': keras.optimizers.Adam(learning_rate=1e-3),
    'loss': keras.losses.BinaryCrossentropy(),# Get new error if we change loss to this: 'sparse_categorical_crossentropy',
    'metrics': [keras.metrics.SparseCategoricalAccuracy()],
}

In [108]:
model = create_model(baseline_layers_info, compile_info)

Found 3 total layers
Model: "sequential_19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_layer (Embedding)  (None, 2900, 50)         20164550  
                                                                 
 bidirectional_3 (Bidirectio  (None, 128)              58880     
 nal)                                                            
                                                                 
 Dense_layer (Dense)         (None, 46)                5934      
                                                                 
Total params: 20,229,364
Trainable params: 20,229,364
Non-trainable params: 0
_________________________________________________________________


## Train model

In [109]:
# output matrix (y) has extra 3rd dimension added because sparse cross-entropy function requires one label per row
model.fit(x=x_train, y=y_train, 
          batch_size=20, epochs=10)

Epoch 1/10


ValueError: in user code:

    File "/usr/local/lib/python3.9/site-packages/keras/engine/training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.9/site-packages/keras/engine/training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.9/site-packages/keras/engine/training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.9/site-packages/keras/engine/training.py", line 809, in train_step
        loss = self.compiled_loss(
    File "/usr/local/lib/python3.9/site-packages/keras/engine/compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/usr/local/lib/python3.9/site-packages/keras/losses.py", line 141, in __call__
        losses = call_fn(y_true, y_pred)
    File "/usr/local/lib/python3.9/site-packages/keras/losses.py", line 245, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/usr/local/lib/python3.9/site-packages/keras/losses.py", line 1807, in binary_crossentropy
        backend.binary_crossentropy(y_true, y_pred, from_logits=from_logits),
    File "/usr/local/lib/python3.9/site-packages/keras/backend.py", line 5158, in binary_crossentropy
        return tf.nn.sigmoid_cross_entropy_with_logits(labels=target, logits=output)

    ValueError: `logits` and `labels` must have the same shape, received ((20, 46) vs (20, 2900)).


In [47]:
y_train.shape

(100, 2900)

In [48]:
x_train.shape

(100, 2900)